### PR TITLE
[IMP] Port Scanner Multi-threaded-Works 10x faster

### PR DESCRIPTION
**Pull request by srcecde**
Hi,

I have made the port scanner multi-threaded. Now it returns results more faster then before. No long waiting for results.

### CODE REVIEW

**Comment by Ekultek** [comment]
Please update `run_scn_thread` to (`RunScanThread`), that way it is camel cased via PEP8 https://www.python.org/dev/peps/pep-0008/#naming-conventions.

After this is done, I'll merge the request

**Review by Ekultek — COMMENTED** [review]
Please update run_scn_thread to (RunScanThread), that way it is camel cased via PEP8 https://www.python.org/dev/peps/pep-0008/#naming-conventions. also move the threading import needs to be above the library imports

```
...
import threading
from lib.core.settings import LOGGER
....
```
So all together the changes should reflect this:

```
import socket
import time
import Queue
import threading
from lib.core.settings import LOGGER
from lib.core.settings import RESERVED_PORTS


class PortScanner(object):
    
    ...

class RunScanThread(PortScanner):

    ...
```
After this is done, I'll merge the request

**Comment by srcecde** [comment]
Hi
I have fixed

**Comment by Ekultek** [comment]
accepted

**Pull request merged**
