### PR TITLE
Mas dev

### PR DESCRIPTION
**Pull request by srcecde**
Fixed file path of dorks finder. Previously the file is saved outside the created folder. I have fixed that issue.

### CODE REVIEW

**Comment by Ekultek** [comment]
I'm about to push a really big update out today, so if this could wait till that's done, I'll take a look at it from there, thanks.

**Comment by srcecde** [comment]
Ya sure. No issues.

**Comment by Ekultek** [comment]
what is the point of this request?

**Comment by Ekultek** [comment]
As of now (I just tried to your way and the original way) I see no correlation or issues with the file being saved outside of the directory, this was however, an issue about three days ago, but update 1.0.6.9 took care of that. The way the application stands now is sufficient, unless you're talking about the cookie file I don't see any problems with how it is right now?

**Review by Ekultek — COMMENTED** [review]
As of now (I just tried it your way and the original way) I see no correlation or issues with the file being saved outside of the directory, this was however, an issue about three days ago, but update 1.0.6.9 took care of that. The way the application stands now is sufficient, unless you're talking about the cookie file I don't see any problems with how it is right now?

**Comment by Ekultek** [comment]
Closing this down

**Pull request closed without merging**
